version: '3'

services:
  workshop-db:
    container_name: psql-workshop-prototype
    image: library/postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=s4fePassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
